/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BoxCodeImport } from './routes/box/$code'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BoxCodeRoute = BoxCodeImport.update({
  id: '/box/$code',
  path: '/box/$code',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/box/$code': {
      id: '/box/$code'
      path: '/box/$code'
      fullPath: '/box/$code'
      preLoaderRoute: typeof BoxCodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/box/$code': typeof BoxCodeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/box/$code': typeof BoxCodeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/box/$code': typeof BoxCodeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/box/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/box/$code'
  id: '__root__' | '/' | '/box/$code'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxCodeRoute: typeof BoxCodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxCodeRoute: BoxCodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/box/$code"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/box/$code": {
      "filePath": "box/$code.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
